### ISSUE TITLE
Graceful cancellation not working?

### ISSUE THREAD

**Issue by f3ath** [machinescream/worker_manager#105]
Hi @machinescream 

If I interpret this part of the readme correctly

> lambda function that can be called periodically within the task to check if it should be cancelled. This allows tasks to clean up and terminate gracefully.

calling `.cancel()` is supposed to let the worker finish its stuff and exit gracefully. However I can't get the expected result.

Here's the code I'm running
```dart
import 'dart:io';

import 'package:worker_manager/worker_manager.dart';

void main() async {
  final worker = workerManager.executeGentle<void>((isCanceled) async {
    while (!isCanceled()) {
      print('Worker is running...');
      await Future.delayed(const Duration(seconds: 1));
    }
    print('Gracefully stopping worker...');
  });
  print('Worker started.');

  ProcessSignal.sigint.watch().listen((event) async {
    print('SIGINT received. Shutting down...');
    worker.cancel();
    print('Worker canceled, waiting for completion...');
    await worker.onError((_, __) {});
    print('Worker completed.');
    exit(0);
  });
  print('SIGINT handler registered.');
}
```
 and here's the result I'm getting:
 ```
 [f3ath@rivendell server]$ dart bin/wrkr.dart 
Worker started.
SIGINT handler registered.
Worker is running...
Worker is running...
Worker is running...
Worker is running...
^CSIGINT received. Shutting down...
Worker canceled, waiting for completion...
Worker completed.
[f3ath@rivendell server]$ 
```

I would expect it to print "Gracefully stopping worker..." before it exits, but it won't. Please help me understand what I'm doing wrong.

On a side note, why is cancellation resulting in a `CanceledError` getting thrown? I had to slap that ugly `.onError((_, __) {})` thing to silence the exception.

**Comment by machinescream** [comment]
> Hi @machinescream
> 
> If I interpret this part of the readme correctly
> 
> > lambda function that can be called periodically within the task to check if it should be cancelled. This allows tasks to clean up and terminate gracefully.
> 
> calling `.cancel()` is supposed to let the worker finish its stuff and exit gracefully. However I can't get the expected result.
> 
> Here's the code I'm running
> 
> ```dart
> import 'dart:io';
> 
> import 'package:worker_manager/worker_manager.dart';
> 
> void main() async {
>   final worker = workerManager.executeGentle<void>((isCanceled) async {
>     while (!isCanceled()) {
>       print('Worker is running...');
>       await Future.delayed(const Duration(seconds: 1));
>     }
>     print('Gracefully stopping worker...');
>   });
>   print('Worker started.');
> 
>   ProcessSignal.sigint.watch().listen((event) async {
>     print('SIGINT received. Shutting down...');
>     worker.cancel();
>     print('Worker canceled, waiting for completion...');
>     await worker.onError((_, __) {});
>     print('Worker completed.');
>     exit(0);
>   });
>   print('SIGINT handler registered.');
> }
> ```
> 
> and here's the result I'm getting:
> 
> ```
> [f3ath@rivendell server]$ dart bin/wrkr.dart 
> Worker started.
> SIGINT handler registered.
> Worker is running...
> Worker is running...
> Worker is running...
> Worker is running...
> ^CSIGINT received. Shutting down...
> Worker canceled, waiting for completion...
> Worker completed.
> [f3ath@rivendell server]$ 
> ```
> 
> I would expect it to print "Gracefully stopping worker..." before it exits, but it won't. Please help me understand what I'm doing wrong.
> 
> On a side note, why is cancellation resulting in a `CanceledError` getting thrown? I had to slap that ugly `.onError((_, __) {})` thing to silence the exception.

Hi, thank you for the feedback.
It is really interesting behavior you are facing on. It seems like isolate - is a child process of the main application process and it's getting shutdown by calling SIGINT() to main process of application.
That's why you don't see gracefully cancelled print.
About canceled error: to finish awaited value from completer, we should complete it with error or value.
Since completing with null if worker is canceled -  is definitely wrong behavior and pushes user to handle with null, it's throwing exception. I understand your pain about handling error every time, I could suggest you to write some extension over Cancellable class to skip CancelledError handling, cheers!

**Comment by machinescream** [comment]
> > Hi @machinescream
> > If I interpret this part of the readme correctly
> > > lambda function that can be called periodically within the task to check if it should be cancelled. This allows tasks to clean up and terminate gracefully.
> > 
> > 
> > calling `.cancel()` is supposed to let the worker finish its stuff and exit gracefully. However I can't get the expected result.
> > Here's the code I'm running
> > ```dart
> > import 'dart:io';
> > 
> > import 'package:worker_manager/worker_manager.dart';
> > 
> > void main() async {
> >   final worker = workerManager.executeGentle<void>((isCanceled) async {
> >     while (!isCanceled()) {
> >       print('Worker is running...');
> >       await Future.delayed(const Duration(seconds: 1));
> >     }
> >     print('Gracefully stopping worker...');
> >   });
> >   print('Worker started.');
> > 
> >   ProcessSignal.sigint.watch().listen((event) async {
> >     print('SIGINT received. Shutting down...');
> >     worker.cancel();
> >     print('Worker canceled, waiting for completion...');
> >     await worker.onError((_, __) {});
> >     print('Worker completed.');
> >     exit(0);
> >   });
> >   print('SIGINT handler registered.');
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and here's the result I'm getting:
> > ```
> > [f3ath@rivendell server]$ dart bin/wrkr.dart 
> > Worker started.
> > SIGINT handler registered.
> > Worker is running...
> > Worker is running...
> > Worker is running...
> > Worker is running...
> > ^CSIGINT received. Shutting down...
> > Worker canceled, waiting for completion...
> > Worker completed.
> > [f3ath@rivendell server]$ 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would expect it to print "Gracefully stopping worker..." before it exits, but it won't. Please help me understand what I'm doing wrong.
> > On a side note, why is cancellation resulting in a `CanceledError` getting thrown? I had to slap that ugly `.onError((_, __) {})` thing to silence the exception.
> 
> Hi, thank you for the feedback. It is really interesting behavior you are facing on. It seems like isolate - is a child process of the main application process and it's getting shutdown by calling SIGINT() to main process of application. That's why you don't see gracefully cancelled print. About canceled error: to finish awaited value from completer, we should complete it with error or value. Since completing with null if worker is canceled - is definitely wrong behavior and pushes user to handle with null, it's throwing exception. I understand your pain about handling error every time, I could suggest you to write some extension over Cancellable class to skip CancelledError handling, cheers!

I think I misunderstood your code. 
The whole think is going here
https://github.com/machinescream/worker_manager/blob/d854625e485b9152a1337fa0855d7f1b0e605eff/lib/src/worker/worker_io.dart#L112
You can see that isolate is not getting killed, it throws and sending cancelled error over the port.
I will write test to check this behavior

**Comment by machinescream** [comment]
@f3ath I wrote test to check is everything fine with gentle cancel, here some code to examine on.
<img width="676" alt="Screenshot 2024-09-27 at 15 02 41" src="https://github.com/user-attachments/assets/e746cd2e-c467-4bd6-8405-faf7c60ca18a">

**Comment by machinescream** [comment]
Please reopen if necessary
