### ISSUE TITLE
Inconsistent Web Platform Support Listing on pub.dev

### ISSUE THREAD

**Issue by Turskyi** [machinescream/worker_manager#107]
It appears that the worker_manager package lists support for the web platform on pub.dev, but there is no clear documentation or example for web usage. Specifically, I noticed that the [example](https://github.com/machinescream/worker_manager/tree/master/example) project in the GitHub repository **does not include a web** folder, and there is no mention of how the package functions on the web.

<img width="863" alt="Screenshot 2024-09-26 at 11 56 50 AM" src="https://github.com/user-attachments/assets/37f4218c-84c8-47f1-bd79-eeb34033ea24">

Could you clarify whether worker_manager fully supports the web platform? 
If web support is intended, it would be helpful to have some documentation or examples demonstrating how to use the package in a web environment. If not, **it might be a good idea to remove the web platform from the supported platforms** list on pub.dev to avoid confusion.

Thank you!

**Comment by machinescream** [comment]
Hi, yes worker_manager does work in web, but similar to compute method. After isolates support in warm, it should work same as non-web platforms. I am closing this issue and link to "web support docs" new issue, thanks
