### ISSUE TITLE
how to deal with RustLib.init()

### ISSUE THREAD

**Issue by jidanyu** [machinescream/worker_manager#111]
Cancelable<ResultType> cancelable = workerManager.execute<ResultType>(
  () async {
    // Your CPU-intensive function here 
 await RustLib.init()
//.... some work
RustLib.dispose();
  },
  priority: WorkPriority.immediately,
);
when i use workerManager like this  in serval places. i get some error like "please do not RustLib.init() init twice".

What is the correct way to use Rust in workerManager?

**Comment by machinescream** [comment]
I suppose you are calling this 
`RustLib.init()`
Somewhere in the app twice. Simply don't do it.
