### ISSUE TITLE
Could I get all isolates that `worker_manager` created?

### ISSUE THREAD

**Issue by HaloWang** [machinescream/worker_manager#97]
I want to add [sentry](https://sentry.io/) to capture any errors in happened in the isolates created by `worker_manager`.

Based on Sentry.io's doc:

> For your own Isolates, add an [Error Listener](https://api.flutter.dev/flutter/dart-isolate/Isolate/addErrorListener.html) by calling isolate.addSentryErrorListener()

I need to get the isolates created by `worker_manager`

**Comment by machinescream** [comment]
if any errors have been thrown in isolate and you don't handle these errors locally u can catch everything in dart Zone, please use callback from dart Zone to send anything you want to sentry, cheers, closing issue for now, reopen if you don't succeed

**Comment by HaloWang** [comment]
I pretty wonder what is `dart Zone`. Is that 3rd-party framework? Can u give some links about `dart Zone`? Thank you.

**Comment by machinescream** [comment]
> I pretty wonder what is `dart Zone`. Is that 3rd-party framework? Can u give some links about `dart Zone`? Thank you.

you dont need to read everything actually, just wrap your runApp in to zone and catch all unhandler errors there https://dart.dev/articles/archive/zones#handling-uncaught-errors
